### ISSUE TITLE
The outdir in the config does not seem to work

### ISSUE THREAD

**Issue by hsablonniere** [open-wc/custom-elements-manifest#47]
Hey team :wink:

I tried using `outdir` in my `custom-elements-manifest.config.mjs` but the file still gets generated at the default location. Using the CLI param works.

```
export default {
  globs: ['src/**/cc-*.js'],
  // Has no effect for now
  outdir: 'dist',
  plugins: [
  ],
};
```

**Comment by hsablonniere** [comment]
Also, when I specify `--outdir dist` and `dist` does not exist, there's an `ENOENT` error.

**Comment by thepassle** [comment]
Ah, its because the `defaultValue` of `outdir` (from the CLI options) is `''`, and CLI options override user config options;
```js
    const mergedOptions = { ...userConfig, ...cliConfig };
```

And because `outdir` (from CLI options) _has_ a value (`''`), I guess it overrides the user config option 🤦

**Comment by thepassle** [comment]
fixed in https://github.com/open-wc/custom-elements-manifest/pull/49

**Comment by hsablonniere** [comment]
:parrot: :man_dancing:

**Comment by hsablonniere** [comment]
@thepassle There is still an error if the directory does not exist:

> Also, when I specify --outdir dist and dist does not exist, there's an ENOENT error.
